version: '3.8'

services:
  bot:
    build: .
    container_name: utyapal_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./sql_app.db:/app/sql_app.db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
