"""Add shop and bigintel

Revision ID: 02a07008dd9d
Revises: 
Create Date: 2026-07-20 21:31:07.754800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02a07008dd9d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_items_code'), 'shop_items', ['code'], unique=True)
    op.create_index(op.f('ix_shop_items_id'), 'shop_items', ['id'], unique=False)
    op.create_table('user_shop_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('price_paid', sa.Float(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['shop_items.id'], ),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_shop_purchases_id'), 'user_shop_purchases', ['id'], unique=False)
    op.create_index(op.f('ix_user_shop_purchases_item_id'), 'user_shop_purchases', ['item_id'], unique=False)
    op.create_index(op.f('ix_user_shop_purchases_telegram_id'), 'user_shop_purchases', ['telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_shop_purchases_telegram_id'), table_name='user_shop_purchases')
    op.drop_index(op.f('ix_user_shop_purchases_item_id'), table_name='user_shop_purchases')
    op.drop_index(op.f('ix_user_shop_purchases_id'), table_name='user_shop_purchases')
    op.drop_table('user_shop_purchases')
    op.drop_index(op.f('ix_shop_items_id'), table_name='shop_items')
    op.drop_index(op.f('ix_shop_items_code'), table_name='shop_items')
    op.drop_table('shop_items')
    # ### end Alembic commands ###
